DROP TABLE IF EXISTS DRINKS CASCADE;
DROP SEQUENCE IF EXISTS DRNK_SEQ;

CREATE SEQUENCE DRNK_SEQ;

CREATE TABLE DRINKS(
drnk_id INTEGER default nextval('DRNK_SEQ'),
volume INTEGER,
price INTEGER,
title VARCHAR(50) CONSTRAINT drnk_title_nn NOT NULL,
description VARCHAR(200),
CONSTRAINT drnk_id_pk PRIMARY KEY (drnk_id));